### ISSUE TITLE
Volume slider not registering correctly

### ISSUE THREAD

**Issue by Hunanbean** [steveway/papagayo-ng#22]
When first started, the position of the volume slider is at 50%, but the actual volume level is 100%
Also, the volume slider has has no effect on volume level when sliding while the audio file is playing. It does work if set before playback.

Thank you

**Comment by steveway** [comment]
Hi, I updated it so that it will now save the volume you chose.
The volume not changing while it is playing depends on which sound playback backend you are using.
It works with "SoundPlayerNew" but not with the simple "SoundPlayer", which one are you using?
Maybe we can get SoundPlayerNew running on Linux and/or OSX.

**Comment by Hunanbean** [comment]
Sorry, on this windows machine i do not know how to change which sound player is in use.

**Comment by steveway** [comment]
In the current release installer it is set to the old one I believe, because I experimented with QT6 which doesn't support QtMultimedia currently.
If you use the code you can change it by choosing which one get's imported in LipSyncDoc.py
I'll try to create a new installer with SoundPlayerNew.

**Comment by Hunanbean** [comment]
It works as expected with your latest installer

Thank you
