### ISSUE TITLE
Windows Uninstaller only sees most recent install

### ISSUE THREAD

**Issue by Hunanbean** [steveway/papagayo-ng#33]
Windows uninstaller, "programs and features", only lists the latest installation, even though i have several located in different folders.

**Comment by steveway** [comment]
Ah yes, we are always writing to the same registry entry with the Installer.
https://github.com/steveway/papagayo-ng/blob/master/papagayo-ng.nsi
I guess we need to modify our script to also insert the version information.
The usage is explained here kinda:
https://nsis.sourceforge.io/mediawiki/index.php?title=Add_uninstall_information_to_Add/Remove_Programs&oldid=25114
Since during the packaging with PyInstaller we add the version to the .exe file we can get the version from that.
Apparently NSIS has the command getdllversion for that:
https://nsis.sourceforge.io/Docs/Chapter5.html#ppgetdllversion
This should give each version its own entry for the programs and features, but it will still give problems when you install the same version multiple times.
So I guess we would also need to check if that registry key exists for that version already during install and stop the installation then.

**Comment by Hunanbean** [comment]
Perhaps when reinstalling the same version it could trigger a notification and allow overwrite.

**Comment by Hunanbean** [comment]
Apologies for the long absence. I am now entirely on Linux, so i would not be able to tell if this issue is resolved.
